In [1]:
listx = [[3, 4, 8], 
        [2, 6, 7]]

In [2]:
import numpy as np

In [3]:
na = np.array(listx)

In [5]:
print(type(na))

<class 'numpy.ndarray'>


In [6]:
print(na)

[[3 4 8]
 [2 6 7]]


In [7]:
na[1][1]

6

In [9]:
na.ndim

2

In [10]:
na.shape

(2, 3)

In [11]:
na.size

6

In [12]:
na.dtype

dtype('int32')

In [14]:
nb = np.array([[3, 4, "hi"], [10, 12, "hello"]])

In [15]:
print(nb)

[['3' '4' 'hi']
 ['10' '12' 'hello']]


In [16]:
nb.dtype

dtype('<U11')

In [17]:
nc = np.array([10, 20, 30]) 

In [18]:
nc.ndim

1

In [19]:
nc.shape

(3,)

In [20]:
nd = np.zeros((3, 4))

In [21]:
print(nd)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
ne = np.array([[10, 20, 30], [80, 70, 60]])

In [23]:
print(na)

[[3 4 8]
 [2 6 7]]


In [24]:
print(ne)

[[10 20 30]
 [80 70 60]]


In [25]:
na + ne

array([[13, 24, 38],
       [82, 76, 67]])

In [26]:
na**2

array([[ 9, 16, 64],
       [ 4, 36, 49]], dtype=int32)

In [27]:
np.sin(na) 

array([[ 0.14112001, -0.7568025 ,  0.98935825],
       [ 0.90929743, -0.2794155 ,  0.6569866 ]])

In [28]:
print(na**2)

[[ 9 16 64]
 [ 4 36 49]]


In [29]:
na

array([[3, 4, 8],
       [2, 6, 7]])

In [30]:
nf = np.arange(9)

In [31]:
print(nf)

[0 1 2 3 4 5 6 7 8]


In [33]:
nf = np.arange(9)

In [34]:
na.shape

(2, 3)

In [35]:
na.reshape(6, 1)

array([[3],
       [4],
       [8],
       [2],
       [6],
       [7]])

In [36]:
na

array([[3, 4, 8],
       [2, 6, 7]])

In [37]:
ng = np.arange(9).reshape(3,3)

In [38]:
print(ng)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
nh = np.array([[11, 17, 19], [16, 20, 10], [12, 24, 38]])

In [42]:
print(nh)

[[11 17 19]
 [16 20 10]
 [12 24 38]]


In [44]:
print(nh)
print("-----")
print(nh[1][2])

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
10


In [45]:
print(nh)
print("-----")
print(nh[0]) 

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
[11 17 19]


In [46]:
print(nh)
print("-----")
print(nh[0][:2]) 

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
[11 17]


In [49]:
print(nh)
print("-----")
print(nh[1:2][:2]) 

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
[[16 20 10]]


In [51]:
print(nh)
print("-----")
print(nh[1:, :2]) 

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
[[16 20]
 [12 24]]


In [52]:
lista = [12, 24, 36, 48]

lista[1]
lista[1:3]

lista[1:-1]

[24, 36]

In [53]:
print(nh)
print("-----")
print(nh[1:, :2]) 

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
[[16 20]
 [12 24]]


In [54]:
print(nh)
print("-----")
print(nh[1:-1, 1:]) 

[[11 17 19]
 [16 20 10]
 [12 24 38]]
-----
[[20 10]]


In [58]:
np.linspace(2, 6, 4)

array([2.        , 3.33333333, 4.66666667, 6.        ])

In [60]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
13/7
#round(13/7)

1.8571428571428572

In [62]:
round(13/7, 4)

1.8571

In [63]:
print(na)

[[3 4 8]
 [2 6 7]]


In [64]:
ni = na > 4

In [65]:
print(type(ni))

<class 'numpy.ndarray'>


In [66]:
print(ni)

[[False False  True]
 [False  True  True]]


In [67]:
10 > 4

True

In [70]:
np.transpose((na > 4).nonzero())

array([[0, 2],
       [1, 1],
       [1, 2]], dtype=int64)

In [71]:
(na > 4).nonzero()

(array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))

In [72]:
np.argwhere(na>4)

array([[0, 2],
       [1, 1],
       [1, 2]], dtype=int64)

In [73]:
print(np.argwhere(na>4))

[[0 2]
 [1 1]
 [1 2]]
